baseurl = "https://www.mneilsworld.com"
title = "Michael Neil"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "Michael Neil"
  description = '<!--[-->Simple Solutions<!--]--><br /><!--[-->to complex problems<!--]-->'
  logoimage = "/images/icon.png"
  copyright = "Michael Neil"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[languages]
[languages.en]
languageName = "English"
weight = 1
title = "Michael Neil"

[languages.de]
languageName = "Deutsch"
weight = 2
title = "Michael Neil"
description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br /><!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
